// Export all commands
module.exports = {
    sudo: require('./sudo'),
    warn: require('./warn'),
    resetwarning: require('./resetwarning'),
    allowdomain: require('./allowdomain'),
    menu: require('./menu'),
    ping: require('./ping'),
    alive: require('./alive'),
    vv: require('./vv'),
    delete: require('./delete'),
    kick: require('./kick'),
    tagall: require('./tagall'),
    promote: require('./promote'),
    mute: require('./mute'),
    unmute: require('./unmute'),
    left: require('./left'),
    tag: require('./tag'),
    join: require('./join'),
    setgrppp: require('./setgrppp'),
    antilnk: require('./antilnk'),
    sticker: require('./sticker'),
    toimg: require('./toimg'),
    filter: require('./filter'),
    country: require('./country'),
    kill: require('./kill'),
    online: require('./online'),
    block: require('./block'),
    ttdownload: require('./ttdownload'),
    song: require('./song'),
    lyrics: require('./lyrics'),
    weather: require('./weather'),
    movie: require('./movie')
}